### ISSUE TITLE
Add better option coverage

### ISSUE THREAD

**Issue by bddenhartog** [bddenhartog/docker-murmur#12]
Currently, the configuration options do not cover all possible options. Review them and implement options that make sense for a containerized installation of murmur, and allow for those options to be set via environment variables.

Originally this issue stated that the `+x` substitution should be removed. It has been decided that the `+x` substitution **should remain** and be used for variable that we want to determine are set *and not empty*. Refer to [this StackOverflow question](http://stackoverflow.com/questions/3601515/how-to-check-if-a-variable-is-set-in-bash) for more information.

- Resource: https://wiki.mumble.info/wiki/Murmur.ini

**Comment by SISheogorath** [comment]
May take a look at https://github.com/SISheogorath/configmagic which is written exactly for this.

There is a lot to do but basics are done ;)

**Comment by bddenhartog** [comment]
What would be the gain over defining a shell function that calls `sed` in the `docker-murmur` binary?

**Comment by bddenhartog** [comment]
Closed in #29; message not added to merge commit.
