### ISSUE TITLE
Determine better implementation for custom welcometext (and fix readme)

### ISSUE THREAD

**Issue by bddenhartog** [bddenhartog/docker-murmur#30]
Currently, the README suggests that the `welcometext` setting can be set via an environment variable. This was an oversight that occurred in PR #29.

How we're defining the `welcometext` setting needs to be refactored. There is a default value that is overridden by the contents of `/data/welcome.txt`. If the file exists, the setting's default value is wiped out, and the contents of the file are dumped into `/etc/murmur.ini`, with two double quotes wrapped around the (potentially multi-line) welcome message. As part of this process, any double quotes in the file are escaped.

The issue here is that this is not an optimal solution for several reasons:

- It is the only setting blocking us from re-running `docker-murmur` in a container due to the nature of the `ICE` configuration section (the `ICE` config section needs to be last in `murmur.ini`). This isn't a breaking issue, but would be a QOL improvement for users debugging an instance.

- It requires an edit on the filesystem, which isn't a problem on a small scale, but is less ideal than taking an arbitrary value (as in a value from a database)

    - Taking an already-parsed string isn't an issue and would be trivial. Users would implement this by setting some environment variable equal to the data from their database, e.g. `MUMBLE_WELCOMETEXT=parsedContentFromDatabase`, but assuming all data passed to this variable is already parsed and escaped is a silly mistake to make.

One possible -- and likely necessary -- solution is to escape the special characters manually, at least the common ones (including linebreaks). Patterns like `s/(\/|\\|\&|\[|\]|\')/\\\1/g` and `s/\s/ /g` might be good starting points if this approach is taken, but I'm open to other suggestions.

**Comment by bddenhartog** [comment]
@SISheogorath What are your thoughts? Do you see any specific reason to continue supporting the file method of adding `welcometext`?

**Comment by SISheogorath** [comment]
For me the welcometext is like the `Motd` in IRC. So I love multi-line setups which are difficult/creepy to represent in a environment variable. That's why I build it to use a file. And bringing it to the database isn't the best way to hold it somewhere as you need to interact with the database. I like to avoid this. We can may pass it to the database from a file?

To fix the issue itself, rerunning the container, we can just use `murmur.ini.default` and cat everything together by entry-point script.

In the end, as we need to hold the database inside a data container it doesn't matter anyways. And as there is a default message when no file is submitted it doesn't break anything.

**Comment by bddenhartog** [comment]
My reference to a database was centered around the thought of implementing this container in a production environment, where users pay for an instance and have a ui to alter the data. In that scenario, I think parsing the input and storing it in the database makes the *most* sense. In that case, it would be easier to use this image if everything could be passed in as an environment variable; it would make whatever bootstrap script I'm running simple: I'd grab a user's settings from the database, fill out some envvars, and voila

**Comment by bddenhartog** [comment]
I see the appeal from the current use case, though, so I think for now loading from a file makes sense. I'll get a fix out tonight.

**Comment by SISheogorath** [comment]
I agree 😄 

This makes a lot of sense. But currently I can only refer to my own setup which uses systemd to manage docker containers. And placing multi-line environment variables inside a `ExecStart` statement is horrible 😉
