### ISSUE TITLE
Refactor settings table in readme

### ISSUE THREAD

**Issue by bddenhartog** [bddenhartog/docker-murmur#34]
I'd like to be able to clear up the settings table and make it a bit more readable. We could move the links to the environment variables themselves -- for those that link to another section in the readme, they should link there instead of to the remote documentation.

The goal here is to make the table a bit more readable and less cluttered. Currently, some of the longer defaults (like `channelname`, `username`, `ice`) are wrapped -- this is harder to read (especially with a regular expression), and the issue is more convoluted on smaller screens, especially if the particular interface doesn't adjust the table using media queries (e.g. docker hub).

**Comment by mattgd** [comment]
I'm on it!
