### ISSUE TITLE
Suggest better solution for windows users building from source

### ISSUE THREAD

**Issue by bddenhartog** [bddenhartog/docker-murmur#35]
Currently, the readme suggests that Windows users change a global git configuration before cloning the repository, when building the image from source.

Instead, we should suggest that they clone the repository using the following command, which changes a configuration setting for git on-the-fly:

    git -c core.autocrlf=false clone https://github.com/bddenhartog/docker-murmur

**Comment by erikstrottmann** [comment]
Hey @bddenhartog, I tried a different solution for PR #38: a `.gitattributes` file instead of a separate `git clone` command. Let me know what you think!

**Comment by bddenhartog** [comment]
I like this much more! Thanks again!
