### ISSUE TITLE
Add list of contributors

### ISSUE THREAD

**Issue by bddenhartog** [bddenhartog/docker-murmur#40]
Several people have contributed changes to this project; they should be recognized in a `CONTRIBUTORS.md` file.

Does [this](https://github.com/mgechev/github-contributors-list) work for generating a markdown table? Would be much cooler than just a list, although I have not explored that project at all and am not sure if displaying photos + username is ideal.

**Comment by jameskolce** [comment]
I could help with this!

**Comment by bddenhartog** [comment]
@jameskolce Please see #41 and #43 -- thanks though!

I'll add a notice to the readme requesting that people comment on an issue prior to working on it to avoid issues like this ;)

**Comment by jameskolce** [comment]
Alright! fortunately I didn't have started yet haha. But yeah, that's not a problem 👍

**Comment by bddenhartog** [comment]
Decided against doing this for purposes of maintenance. Contributors are easily viewed through Github's UI, anyhow.
