### ISSUE TITLE
Remove unecessary MUMBLE_ICE envvar in Makefile

### ISSUE THREAD

**Issue by bddenhartog** [bddenhartog/docker-murmur#45]
It seems that I accidentally left a `MUMBLE_ICE` definition in the `debug` target of the Makefile. This should be removed. Additionally, the `.DEFAULT` definition should be removed. A new target should be added as the first target, named `default`, that depends on `build` and `run`, but does not have a body of its own.

**Comment by alexmdodge** [comment]
I'd be happy to take a look at this!

**Comment by alexmdodge** [comment]
Note that I was working under an internet connection which was throwing,

    Connecting to github.com (192.30.253.113:443) 
    wget: error getting response: Connection reset by peer
    bzcat: invalid magic
    tar: short read

in terms of errors. The build check passed so let me know if there is anything I missed or any changes!

**Comment by bddenhartog** [comment]
It would seem that you were not able to download the `murmur` binary from github (this happens as part of the build process for the image); rest assured that isn't caused by any change you're making. I'd guess your networking isn't set up for the Docker daemon is all.
